version: "3.8"
services:
  db:
    image: postgres:12
    # restart: always
    container_name: postgres-contain
    environment:
      POSTGRES_DB: cfc
      POSTGRES_PASSWORD: ola

    # volumes:
    #   - ./db-data:/var/lib/postgresql/data

    ports:
      - 5432:5432

    # networks:- 

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ola-server
    depends_on:
      - db
    # restart: always
    container_name: compose_backend
    ports:
      - 3000:3000

    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_DATABASE: postgres
      DB_PASSWORD: ola


    # volumes:- 
    # networks: