version: "3.8"
services:
  db:
    image: postgres:12
    restart: always
    container_name: postgres-contain

    # volumes:- db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: cfc
      POSTGRES_PASSWORD: ola
    # networks:- 

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ola-server
    restart: always
    container_name: compose_backend

    # volumes:- 

    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_DATABASE: postgres
      DB_PASSWORD: ola

    # networks:
    ports:
      - 3000:3000